Listen 80
ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/html/Web
    <Directory /var/www/html/Web>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
