services:
  mdb:
    image: mysql:8.0
    container_name: librebooking-mdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: librebooking
      MYSQL_USER: lb_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # host:container
    volumes:
      - type: bind
        source: ./data/mysql
        target: /var/lib/mysql
      - type: bind
        source: ./data/dump.sql
        target: /docker-entrypoint-initdb.d/dump.sql
        read_only: true
    networks: [lbnet]
  pma:
    image: phpmyadmin:5.2-apache
    container_name: librebooking-pma
    restart: unless-stopped
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: mdb # service name of MySQL
      PMA_PORT: 3306
      # Optional: log in as root or your app user
      # PMA_USER: lb_user
      # PMA_PASSWORD: password
      UPLOAD_LIMIT: 256M # allow larger SQL imports
    depends_on:
      mdb:
        condition: service_started
    volumes:
      - type: bind
        source: ./config.user.inc.php
        target: /etc/phpmyadmin/config.user.inc.php
        read_only: true
    networks: [lbnet]

networks:
  lbnet:
    driver: bridge

volumes:
  db_data:
